#!/usr/bin/env ruby

lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "mule_clip/version"
require 'clipboard'

if /(^-v$)|(^--version$)/ =~ (ARGV[0] || "").strip
  puts MuleClip::VERSION
  exit 0
end

if ARGV[0] == 'kill'
  pid = File.read('pid').strip
  Process.kill(:SIGTERM, pid.to_i) && exit
  abort "[#{pid}]: killできず"
end

watching = ARGV[0]
watching = ENV['CLIPBOARD_BIND_FILE'] unless watching

abort 'パスくれ' unless watching

mtime = ''

begin
  Process.daemon(true, true)
  current_pid = Process.pid
  File.open('pid', 'w') {|f| f << Process.pid.to_s }

  while true do
    File.mtime(watching).tap do |mt|
      unless mt == mtime
        Clipboard.copy(File.read(watching))
        mtime = mt
      end
    end
    sleep 1
  end
rescue => e
  File.open('error', 'w') {|f| f << e.message }
end
